@baseURL = http://localhost:3000
@userId = 11
@petId = 7
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6ImFkb3B0ZXIiLCJpYXQiOjE3NTEyNTMxNjUsImV4cCI6MTc1MTI1Njc2NX0.dEUgvL5FLqxONt0Z8IyFxbmQis4v0gP1vKT5ph2jPGc
#####################
### Public routes ###
#####################

### Get available pets
GET {{baseURL}}/pets/available
Content-Type: application/json

### Register user
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "joao da silva",
    "email": "joao123@example.com",
    "password": "senha123",
    "phone": "123456789110",
    "role": "admin"
}

### Register user with invalid role
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "Jonathan Jones",
    "email": "supermoad_2@example.com",
    "password": "senha123",
    "phone": "123456789110",
    "role": "moderator"
}

### Register user with no role (will assign default "adopter")
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "Clara Soaresaa",
    "email": "clara_aaaaaa2daopter@example.com",
    "password": "senha123",
    "phone": "123456789110"
}

### Login admin
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "senha123"
}

### Login adopter
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "clara_adopter@example.com",
    "password": "senha123"
}


########################
### Protected routes ###
########################

######### Users ########

### Get users
GET {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update user
PUT {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jane aaaaaa",
  "email": "jane.3232@example.com",
  "password": "newpassword123",
  "phone": "1234567890",
  "role": "admin"
}

### Delete user
DELETE {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Pets ########
### Get pets
GET {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

### Get pet by id
GET {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Add Pet
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "available",
    "description": "Friendly and energetic"
}

### Add Pet without status will assign available by default
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "available",
    "description": "Friendly and energetic"
}


### Add Pet with adopted as the status
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "adopted",
    "description": "Friendly and energetic"
}

### Edit Pet
PUT {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Jokeraa",
    "age": 4,
    "species": "Casasast",
    "size": "Large",
    "status": "Available",
    "description": "Friendly and energetic"
}

### Delete pet
DELETE {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Adoptions ########
### Get adoptions
GET {{baseURL}}/adoptions
Content-Type: application/json
Authorization: Bearer {{token}}

### Adopt
POST {{baseURL}}/adoptions
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 10,
    "pet_id": 15,
    "adoption_date": "2025-06-24"
}   