@baseURL = http://localhost:3000
@userId = 2
@petId = 2
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSBEb2UiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwicGhvbmUiOiIxMjM0NTY3ODkxMTAiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDk1OTQ1MzMsImV4cCI6MTc0OTU5ODEzM30.Uf6UU1canpdIzbdHVyJE6a1SG0UJWn4KbbFmAVsA2G0

#####################
### Public routes ###
#####################

### Get available pets
GET {{baseURL}}/pets/available
Content-Type: application/json

### Register
POST {{baseURL}}/users/register
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",
    "password": "senha123",
    "phone": "123456789110",
    "role": "admin"
}

### Login
POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "senha123"
}

########################
### Protected routes ###
########################

######### Users ########

### Get users
GET {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update user
PUT {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jane Doene",
  "email": "jane.doene@example.com",
  "password": "newpassword123",
  "phone": "1234567890",
  "role": "admin"
}

### Delete user
DELETE {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Pets ########
### Get pets
GET {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

### Get pet by id
GET {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}
