@baseURL = http://localhost:3000
@userId = 7
@petId = 3
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTI0NzEwMiwiZXhwIjoxNzUxMjUwNzAyfQ.FTKl7WJqJ273Z03ISNXKr_DK3NtoT9j2B2GUR8R-DxU

#####################
### Public routes ###
#####################

### Get available pets
GET {{baseURL}}/pets/available
Content-Type: application/json

### Register user
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",
    "password": "senha123",
    "phone": "123456789110",
    "role": "admin"
}

### Register user with invalid role
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "Jonathan Jones",
    "email": "supermoad_2@example.com",
    "password": "senha123",
    "phone": "123456789110",
    "role": "moderator"
}

### Register user with no role (will assign default "adopter")
POST {{baseURL}}/users/
Content-Type: application/json

{
    "name": "Clara Soares",
    "email": "clara_a2daopter@example.com",
    "password": "senha123",
    "phone": "123456789110"
}

### Login admin
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "senha123"
}

### Login adopter
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "clara_adopter@example.com",
    "password": "senha123"
}


########################
### Protected routes ###
########################

######### Users ########

### Get users
GET {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update user
PUT {{baseURL}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jane aaaaaa",
  "email": "jane.aaaaadoene@example.com",
  "password": "newpassword123",
  "phone": "1234567890",
  "role": "admin"
}

### Delete user
DELETE {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Pets ########
### Get pets
GET {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

### Get pet by id
GET {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Add Pet
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "available",
    "description": "Friendly and energetic"
}

### Add Pet without status will assign available by default
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "available",
    "description": "Friendly and energetic"
}


### Add Pet with adopted as the status
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "age": 3,
    "species": "Dog",
    "size": "Medium",
    "status": "a",
    "description": "Friendly and energetic"
}

### Edit Pet
PUT {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Joker",
    "age": 4,
    "species": "Cat",
    "size": "Large",
    "status": "Available",
    "description": "Friendly and energetic"
}

### Delete pet
DELETE {{baseURL}}/pets/{{petId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Adoptions ########
### Get adoptions
GET {{baseURL}}/adoptions
Content-Type: application/json
Authorization: Bearer {{token}}

### Adopt
POST {{baseURL}}/adoptions
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 3,
    "pet_id": 5,
    "adoption_date": "2025-06-24"
}   